language: node_js

node_js: stable

sudo: false

install: true  # yarn bug

addons:
  firefox: "45.0"

os:
  - linux
#  - osx

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

before_script:
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/radiorabe/raar-ui/npm-debug.log

branches:
  only: master

notifications:
  email: true

cache:
  directories: node_modules

script:
  - npm run test && npm run build.prod.exp

deploy:
  provider: releases
  api_key:
    secure: WyfriNXocwzMoqhnStUu6wD26DCSjrhEU/yzs0rGWI6kprwimCKEAERWBamqMiwmniSKSsH+6czV5UjyuszshFUJBDWc23iEKiWkFO/4WpPmH45msce86JGbngvGoNXnjVYMgFeD9wt1aHCkbey3zXBPcEeV511/1oW6kH7/v07k0EIm1Z4iaodV1JQtB8J0WWrJboGijXI68vNTbBk210XYcJIfa6SIj3qPMEWY+9BXhtwPsD3vWNxbPaJ8YcJhfdr8l9px45nxzTQAgDh9HGBB6c6yRAAuCH/uf+tajCayC9gZ++t4UNwR2PO+lelH16h2ur15F4n/ABFOqHar2E/jXLfFWNWd7XMWq8ApeZutqS0V5AOaNeWmbfieG8ww5Ha7SxwUdNazq8rS7gyQMdNfOILNivAIX/IRa2rxmgty3WXjqxG/s6yEKiQ1HNdCRxb4zoan0P2n2naDsVScCq14DJYqjsSRWuNCBX9vl2T8Rb3IH/ZoSYd7rjJuSNLM02/bdoUDBYa3osGOpaQDmmrK82iEqazbB7ZVgEJxJeLc/jZXLvlV+Gcsq65V/T8+7Ifw/YOrEYdKOekkQRJBf0uX8SYM6uKpmpVaxZLYtonKT9gVlurKrLp1M+OSqUSODHTb37uot4qI0e5CM6QfAwVJi/eIUi09zi1ymP21T54=
  file: dist/raar-ui.tar.gz
  skip_cleanup: true
  on:
    tags: true
    repo: radiorabe/raar-ui
